### ISSUE TITLE
CLI repository archived. What, if anything, replaces it?

### ISSUE THREAD

**Issue by davidfetter** [ProtonVPN/python-proton-core#1]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [X] This is not a report about my app not working as expected

----------------------------------------

I have scripts that used on the now-obsolete protonvpn-cli. Is there something to replace it, or do I need to cobble something together out of this new flock of Python APIs?

**Comment by calexandru2018** [comment]
Hey @davidfetter , if you require the CLI then it's just a matter of removing the current meta-package (protonvpn if you just upgraded) and installing protonvpn-cli and you should be good to go. We'll be working on a CLI based on this new software architecture in the coming months but have no ETA at the moment.

**Comment by davidfetter** [comment]
> Hey @davidfetter , if you require the CLI then it's just a matter of removing the current meta-package (protonvpn if you just upgraded) and installing protonvpn-cli and you should be good to go.

Isn't that the older one that's no longer being maintained, including the kind of maintenance that might fix security bugs?

> We'll be working on a CLI based on this new software architecture in the coming months but have no ETA at the moment.

I'm thinking that's a thing y'all should have thought about before putting the CLI repository into archive mode. Maybe it's time to bring it back out until such time as you can actually replace it.

**Comment by alexandrevicenzi** [comment]
The best CLI replacement, for now, would be OpenVPN or WireGuard itself, you can download the configs from your Proton dashboard.

While the GitHub repositories have been archived, for openSUSE, the packages will be maintained until there's a new CLI, or until it becomes impossible to maintain and I give up (probably soon since I already had to patch a few things).
