### ISSUE TITLE
Please make tags for releases

### ISSUE THREAD

**Issue by Luciogi** [ProtonVPN/python-proton-core#2]
I found these repositories does not have tags, Kindly add tags :)
https://github.com/ProtonVPN/python-proton-core
https://github.com/ProtonVPN/python-proton-vpn-logger
https://github.com/ProtonVPN/python-proton-vpn-killswitch

**Comment by calexandru2018** [comment]
I'm working on it, should be all available by the end of the week.

**Comment by calexandru2018** [comment]
All tags and releases were created.

**Comment by alexandrevicenzi** [comment]
@calexandru2018 did you push your tags? I dont see any tags or releases
